---
# DotGit Sync Configuration
# ------------------------------------------------------------------------------
dotgit:
  source:
    git:
      url: https://framagit.org/rdeville-public/programs/dotgit-sync-templates
      ref: main
  yaml:
    merge: only
    only:
      - .pre-commit-config.yaml
      - gitlab-ci.yaml

# Repos description and template usage configuration
# ------------------------------------------------------------------------------
name: DotGit Sync
slug: dotgit-sync
description: |-
  Repository helping to manage dotfile for accross git repos in an unified ways.
licenses:
  date:
    first_year: "2023"
  copyright:
    owner: &fullname Romain Deville
    email: &email code@romaindeville.fr
  primary: MIT
  secondaries:
    - BEERWARE
maintainers:
  - name: *fullname
    mail: *email
gitignore:
  templates:
    - base
    - python
statics:
  - base
  - base-ci-gitlab
  - base-pre-commit
  - commitlint-pre-commit
  - markdown
  - markdown-pre-commit
  - markdown-ci-gitlab
  - python
  - python-ci-gitlab
templates:
  - base
  - python
  - nix-flake
  - nix-home-manager-module

# Everything below is only used as variables in templates
# ------------------------------------------------------------------------------
code_of_conduct:
  abuse: abuse+code@romaindeville.fr
extra:
  maintainers:
    Romain Deville:
      socials:
        Website:
          alt: &website https://romaindeville.fr
          url: *website
        Github:
          alt: "@rdeville"
          url: https://github.com/rdeville
        Gitlab:
          alt: "@r.deville"
          url: https://gitlab.com/r.deville
        Framagit:
          alt: "@rdeville"
          url: https://framagit.org/rdeville
  repo:
    url: https://framagit.org/rdeville-public/programs/dotgit-sync
    slug: dotgit-sync
