# BEGIN DOTGIT-SYNC MANAGED BLOCK
default_stages:
  - pre-commit

repos:
# General pre-commit applied every times
# ------------------------------------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
        # Prevents giant files from being committed.
      - id: check-added-large-files
        # Forbids files which have a utf-8 byte-order marker.
      - id: check-byte-order-marker
        # Checks for files that would conflict in case-insensitive filesystems.
      - id: check-case-conflict
        # Ensures that (non-binary) executables have a shebang.
      - id: check-executables-have-shebangs
        # Checks json files for parseable syntax.
      - id: check-json
        # Sets a standard for formatting json files.
      - id: pretty-format-json
        args:
          - --no-sort-keys
        # Checks for files that contain merge conflict strings.
      - id: check-merge-conflict
        # Checks for symlinks which do not point to anything.
      - id: check-symlinks
        # Checks toml files for parseable syntax.
      - id: check-toml
        # Checks yaml files for parseable syntax.
      - id: check-yaml
        # Detects the presence of private keys.
      - id: detect-private-key
        # Ensures that a file is either empty, or ends with one newline.
      - id: end-of-file-fixer
        # Removes utf-8 byte order marker.
      - id: fix-byte-order-marker
        # Prevents addition of new git submodules.
      - id: forbid-new-submodules
        # Forbids any submodules in the repository
      - id: forbid-submodules
        # Don't commit to branch
      - id: no-commit-to-branch
        # Trims trailing whitespace.
      - id: trailing-whitespace
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.7.0
    hooks:
      - id: cspell
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.14.0
    hooks:
        - id: commitlint
          additional_dependencies:
            - gitmojis
          stages:
            - commit-msg
# END DOTGIT-SYNC MANAGED BLOCK
