# BEGIN DOTGIT-SYNC BLOCK MANAGED YAML_MERGED_ENFORCED
Python Linter:
  image: python:3.12-alpine
  stage: lint
  before_script: &id001
  - apk add --update --no-cache git binutils
  - pip install poetry
  - poetry install
  script:
  - poetry run ruff check
  rules: &id002
  - if: $CI_PIPELINE_SOURCE =~ /(parent_pipeline|pipeline)/
    when: never
  - when: always
Python Build:
  image: python:3.12-alpine
  stage: build
  needs:
  - Python Linter
  before_script: *id001
  script:
  - poetry run pyinstaller --clean --noconfirm --log-level WARN pyinstaller.spec
  - poetry build
  rules: *id002
Python Tests Suite:
  image: python:3.12-alpine
  stage: test
  needs:
  - Python Build
  before_script: *id001
  script:
  - poetry run coverage run -m pytest
  - poetry run coverage json
  - poetry run coverage-threshold --config .coverage-threshold.toml
  - poetry run coverage report
  rules: *id002
Python Publish:
  image: python:3.12-alpine
  stage: post-release
  before_script: *id001
  script:
  - poetry publish
  rules:
  - if: $CI_PIPELINE_SOURCE =~ /(parent_pipeline|pipeline)/
    when: never
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    when: always
# END DOTGIT-SYNC BLOCK MANAGED YAML_MERGED_ENFORCED
