---
map:
  source:
    include: source
  dotgit:
    include: dotgit
  name:
    include: required_str
  description:
    include: required_str
  maintainers:
    include: maintainers
  licenses:
    include: licenses
  statics:
    include: list_str
  templates:
    include: list_str
  gitignore:
    include: gitignore
  regex;(.*):
    type: any
