---
map:
  version:
    type: str
    enum:
      - v0
      - v1alpha1
  dotgit:
    include: dotgit
  name:
    include: required_str
  slug:
    include: required_str
  description:
    include: required_str
  maintainers:
    include: maintainers
  licenses:
    include: licenses
  gitignore:
    include: gitignore
  statics:
    include: list_str
  templates:
    include: list_str
  regex;(.*):
    type: any
